// Code generated by protoc-gen-go. DO NOT EDIT.
// source: HelloService.proto

package HelloService_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//The request message containing the user's name
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num1                 int32    `protobuf:"varint,2,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int32    `protobuf:"varint,3,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df26df2ba82d0569, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *HelloRequest) GetNum2() int32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

//The response message
type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df26df2ba82d0569, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloService_proto.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloService_proto.HelloResponse")
}

func init() { proto.RegisterFile("HelloService.proto", fileDescriptor_df26df2ba82d0569) }

var fileDescriptor_df26df2ba82d0569 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x89, 0x3f, 0xab, 0x0e, 0x7a, 0x70, 0x0e, 0x12, 0x04, 0xa1, 0xee, 0x69, 0x4f, 0x01,
	0xab, 0x2f, 0xe0, 0x9e, 0xc4, 0x8b, 0xa5, 0x7d, 0x80, 0x12, 0xcb, 0x50, 0x0b, 0x49, 0x13, 0x33,
	0xad, 0xe8, 0xdb, 0x4b, 0xd3, 0x54, 0x2a, 0x82, 0xb7, 0x99, 0x8f, 0x99, 0x8f, 0x0f, 0xf0, 0x89,
	0x8c, 0x71, 0x15, 0x85, 0x8f, 0xae, 0x21, 0xe5, 0x83, 0x1b, 0x1c, 0xfe, 0x62, 0x75, 0x64, 0xdb,
	0x67, 0x38, 0x8f, 0xb4, 0xa4, 0xf7, 0x91, 0x78, 0x40, 0x84, 0xa3, 0x5e, 0x5b, 0x92, 0x22, 0x13,
	0xbb, 0xb3, 0x32, 0xce, 0x91, 0x8d, 0xf6, 0x4e, 0x1e, 0x64, 0x62, 0x77, 0x5c, 0xc6, 0x39, 0xb1,
	0x5c, 0x1e, 0xfe, 0xb0, 0x7c, 0xfb, 0x08, 0x17, 0xc9, 0xc5, 0xde, 0xf5, 0x4c, 0x28, 0xe1, 0xc4,
	0x12, 0xb3, 0x6e, 0x17, 0xdf, 0xb2, 0xe2, 0x15, 0x6c, 0x02, 0xf1, 0x68, 0x86, 0x24, 0x4d, 0x5b,
	0x5e, 0xa7, 0x9c, 0x14, 0x89, 0x2f, 0x70, 0x5a, 0xe9, 0xaf, 0x88, 0x30, 0x53, 0x7f, 0xfb, 0xd5,
	0x3a, 0xfe, 0xfa, 0xf6, 0x9f, 0x8b, 0x39, 0x69, 0xff, 0x00, 0x37, 0x9d, 0x53, 0x6d, 0xf0, 0x8d,
	0xa2, 0x4f, 0x6d, 0xbd, 0x21, 0x56, 0x6f, 0xd3, 0x05, 0xcf, 0x4f, 0xfb, 0xcb, 0xb5, 0xa2, 0x98,
	0x0c, 0x85, 0x78, 0xdd, 0x44, 0xd5, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xde, 0xdd,
	0x19, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/HelloService_proto.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloService_proto.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloService_proto.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "HelloService.proto",
}
